### ISSUE TITLE
failed stack delete for Custom::AWSCDK-EKS-KubernetesPatch

### ISSUE THREAD

**Issue by igable** [aws-quickstart/quickstart-eks-cdk-python#26]
When attempting to clean up a deployment made via CodeBuild I encountered a failed CloudFormation stack delete on the resource type Custom::AWSCDK-EKS-KubernetesPatch.

The specific resources that don't delete are:

CNIPatchDaemonSet
CNIPatchClusterRoleBinding
CNIPatchClusterRole

I'm using the version at commit 2357e76400a947f40e258242f3edc2c64e30cfe8 (what was at the HEAD of main on 2021-10-11)

All other resources appear to have deleted just fine.

Here is what I did:

```
(venv) ➜  cluster-bootstrap git:(feature/refarch) ✗ npx cdk destroy
Are you sure you want to delete: EKSClusterStack (y/n)? y
EKSClusterStack: destroying...
2:46:07 PM | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesPatch    | CNIPatchDaemonSetEE8CB6E8
Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (NotFound): daemonsets.apps "aws-node" not found\n'

Logs: /aws/lambda/EKSClusterStack-awscdkawseksKubect-Handler886CB40B-t8F2UzkPU8ct

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 19bfc40c-ac25-4398-864b-16ac18333de2)

	new CustomResource (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/core/lib/custom-resource.js:30:25)
	\_ new KubernetesPatch (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/aws-eks/lib/k8s-patch.js:37:9)
	\_ /private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:58
	\_ Kernel._wrapSandboxCode (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8860:24)
	\_ Kernel._create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:34)
	\_ Kernel.create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8173:29)
	\_ KernelHost.processRequest (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9757:36)
	\_ KernelHost.run (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9720:22)
	\_ Immediate._onImmediate (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9721:46)
	\_ processImmediate (internal/timers.js:461:21)

2:46:07 PM | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesPatch    | CNIPatchClusterRole49020577
Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "aws-node" not found\n'

Logs: /aws/lambda/EKSClusterStack-awscdkawseksKubect-Handler886CB40B-t8F2UzkPU8ct

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 81045aea-bc0e-4001-83e7-e749e3291cc9)

	new CustomResource (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/core/lib/custom-resource.js:30:25)
	\_ new KubernetesPatch (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/aws-eks/lib/k8s-patch.js:37:9)
	\_ /private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:58
	\_ Kernel._wrapSandboxCode (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8860:24)
	\_ Kernel._create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:34)
	\_ Kernel.create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8173:29)
	\_ KernelHost.processRequest (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9757:36)
	\_ KernelHost.run (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9720:22)
	\_ Immediate._onImmediate (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9721:46)
	\_ processImmediate (internal/timers.js:461:21)

2:46:08 PM | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesPatch    | CNIPatchClusterRoleBinding0AD58FDA
Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "aws-node" not found\n'

Logs: /aws/lambda/EKSClusterStack-awscdkawseksKubect-Handler886CB40B-t8F2UzkPU8ct

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 00c155c4-e582-4ff5-b2bc-2de9ebec0e7a)

	new CustomResource (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/core/lib/custom-resource.js:30:25)
	\_ new KubernetesPatch (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/jsii-kernel-iyXbFC/node_modules/@aws-cdk/aws-eks/lib/k8s-patch.js:37:9)
	\_ /private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:58
	\_ Kernel._wrapSandboxCode (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8860:24)
	\_ Kernel._create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8432:34)
	\_ Kernel.create (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:8173:29)
	\_ KernelHost.processRequest (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9757:36)
	\_ KernelHost.run (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9720:22)
	\_ Immediate._onImmediate (/private/var/folders/0k/_fn1_sl50wgf1l5nw8v3k3vc0000gn/T/tmp8_0a2s1c/lib/program.js:9721:46)
	\_ processImmediate (internal/timers.js:461:21)


 ❌  EKSClusterStack: destroy failed Error: The stack named EKSClusterStack is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [CNIPatchDaemonSetEE8CB6E8, CNIPatchClusterRoleBinding0AD58FDA, CNIPatchClusterRole49020577]. )
    at Object.waitForStackDelete (/Users/igable/code/quickstart-eks-cdk-python/cluster-bootstrap/node_modules/aws-cdk/lib/api/util/cloudformation.ts:277:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.destroyStack (/Users/igable/code/quickstart-eks-cdk-python/cluster-bootstrap/node_modules/aws-cdk/lib/api/deploy-stack.ts:438:28)
    at CdkToolkit.destroy (/Users/igable/code/quickstart-eks-cdk-python/cluster-bootstrap/node_modules/aws-cdk/lib/cdk-toolkit.ts:264:9)
    at initCommandLine (/Users/igable/code/quickstart-eks-cdk-python/cluster-bootstrap/node_modules/aws-cdk/bin/cdk.ts:225:9)
The stack named EKSClusterStack is in a failed state. You may need to delete it from the AWS console : DELETE_FAILED (The following resource(s) failed to delete: [CNIPatchDaemonSetEE8CB6E8, CNIPatchClusterRoleBinding0AD58FDA, CNIPatchClusterRole49020577]. )
```

**Comment by jasonumiker** [comment]
I am going to play around with https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.core/RemovalPolicy.html and see if setting this to retain fixes this...
